# Generated by Django 5.2.5 on 2025-08-22 11:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('position', models.CharField(choices=[('hero', 'Hero (bosh sahifa katta banner)'), ('top', 'Top (sahifa ustida)'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('carousel', 'Carousel'), ('custom', 'Custom')], default='hero', max_length=30)),
                ('order', models.IntegerField(default=0, help_text='Bir nechta banner bo`lsa tartib')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, help_text='Agar belgilansa, shu vaqtdan keyin banner yopiladi', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
    ]
