# Generated by Django 5.2.5 on 2025-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_rating_content_type_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='hls_playlist_url',
            field=models.URLField(blank=True, help_text='HLS playlist (m3u8) URL', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='hls_segment_path',
            field=models.CharField(blank=True, help_text='HLS segmentlar joylashuvi', max_length=500, null=True),
        ),
    ]
