# Generated by Django 5.2.5 on 2025-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_moviefile_hls_playlist_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='hls_playlist_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
