# Generated by Django 5.2.5 on 2025-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reel_hls_playlist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('director', 'Director')], default='user', max_length=10),
        ),
    ]
