# Generated by Django 5.2.5 on 2025-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_likereels'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('serial', 'Serial')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='episode',
            field=models.PositiveIntegerField(blank=True, help_text="Agar serial bo'lsa, qaysi epizod", null=True),
        ),
        migrations.AddField(
            model_name='moviefile',
            name='season',
            field=models.PositiveIntegerField(blank=True, help_text="Agar serial bo'lsa, qaysi mavsum", null=True),
        ),
    ]
