# Generated by Django 5.2.5 on 2025-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_movie_type_moviefile_episode_moviefile_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefile',
            name='hls_playlist_url',
            field=models.CharField(blank=True, help_text='HLS playlist (m3u8) URL', max_length=2000, null=True),
        ),
    ]
