# Generated by Django 5.2.5 on 2025-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_movie_actors_movie_country_movie_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_banner',
            field=models.ImageField(blank=True, null=True, upload_to='category_banners/'),
        ),
    ]
