# Generated by Django 5.2.5 on 2025-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_category_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_tablet',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('hero', 'Hero (bosh sahifa katta banner)'), ('top', 'Top (sahifa ustida)'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('carousel', 'Carousel'), ('custom', 'Custom'), ('advertisement', 'Advertisement')], default='hero', max_length=30),
        ),
    ]
