# Generated by Django 5.2.5 on 2025-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_testquestion_course_certificate_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='hls_playlist_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='hls_segment_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
