# Generated by Django 5.2.5 on 2025-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_coursevideo_hls_playlist_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category_img', models.ImageField(blank=True, null=True, upload_to='category_course_images/')),
                ('category_banner', models.ImageField(blank=True, null=True, upload_to='category_course_banners/')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.DeleteModel(
            name='CategoryCourse',
        ),
    ]
