# Generated by Django 5.2.5 on 2025-09-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_coursecategory_remove_course_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='app.coursecategory'),
        ),
    ]
