# Generated by Django 5.2.5 on 2025-09-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_course_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
