# Generated by Django 5.2.5 on 2025-09-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_coursetype_coursevideo_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetype',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.channel'),
            preserve_default=False,
        ),
    ]
