# Generated by Django 5.2.5 on 2025-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_coursetype_course_coursetype_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='badge',
            field=models.CharField(blank=True, help_text="Short expertise label, e.g. 'Frontend Development'", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='github',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='telegram',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
