# Generated by Django 5.2.5 on 2025-09-21 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_channel_badge_channel_github_channel_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('seconds_watched', models.PositiveIntegerField(default=0, help_text='Aggregate watched seconds')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='app.coursevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'course_video')},
            },
        ),
    ]
