# Generated by Django 5.2.5 on 2025-09-28 08:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_coursetypeassignment_coursetypetest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='FixCoin miqdori', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Pul toldirish'), ('withdrawal', 'Pul yechish'), ('course_purchase', 'Kurs sotib olish (chiqim)'), ('course_earning', 'Kurs sotishdan daromad (kirim)'), ('transfer_sent', "Pul jo'natish"), ('transfer_received', 'Pul qabul qilish'), ('refund', 'Qaytarib berish'), ('bonus', 'Bonus'), ('penalty', 'Jarima'), ('commission', 'Komissiya (platforma)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Musbat - kirim, manfiy - chiqim', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Tranzaksiyadan keyin balans', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Tranzaksiya tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text="Agar kurs bilan bog'liq bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('from_user', models.ForeignKey(blank=True, help_text="Pul jo'natuvchi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('related_transaction', models.ForeignKey(blank=True, help_text="Bog'langan tranzaksiya", null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.wallettransaction')),
                ('to_user', models.ForeignKey(blank=True, help_text='Pul qabul qiluvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
