# Generated by Django 5.2.5 on 2025-10-01 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_channel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchase_scope',
            field=models.CharField(choices=[('course', "Butun kurs bo'yicha sotib olish"), ('course_type', "Faqat CourseType bo'yicha sotib olish")], default='course', help_text="To'lov qamrovini aniqlaydi: butun kurs yoki CourseType darajasida", max_length=20),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this specific course type. If not set, the course price will be used.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='course_type',
            field=models.ForeignKey(blank=True, help_text="Agar kurs turi bilan bog'liq bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coursetype'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_types', to='app.course'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Pul toldirish'), ('withdrawal', 'Pul yechish'), ('course_purchase', 'Kurs sotib olish (chiqim)'), ('course_type_purchase', 'Kurs turini sotib olish (chiqim)'), ('course_earning', 'Kurs sotishdan daromad (kirim)'), ('course_type_earning', 'Kurs turi sotishdan daromad (kirim)'), ('transfer_sent', "Pul jo'natish"), ('refund', 'Qaytarib berish'), ('bonus', 'Bonus'), ('penalty', 'Jarima'), ('commission', 'Komissiya (platforma)')], max_length=20),
        ),
    ]
