# Generated by Django 5.2.5 on 2025-10-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_course_purchase_scope_coursetype_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoassignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/assignments/'),
        ),
    ]
