# Generated by Django 5.2.5 on 2025-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_videoassignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='reel_type',
            field=models.CharField(choices=[('course', 'Course'), ('channel', 'Channel'), ('movie', 'Movie'), ('course_video', 'Course Video'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='reel',
            name='reel_type_id_or_slug',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
