# Generated by Django 5.2.5 on 2025-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_reel_reel_type_reel_reel_type_id_or_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetypeassignment',
            name='due_days_after_completion',
            field=models.PositiveIntegerField(blank=True, help_text='CourseType dagi barcha videolarni yakunlagandan keyin topshirish uchun beriladigan kunlar soni', null=True),
        ),
    ]
