# Generated by Django 5.2.5 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_coursetypeassignment_due_days_after_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoassignment',
            name='due_days_after_completion',
            field=models.PositiveIntegerField(blank=True, help_text='CourseType dagi barcha videolarni yakunlagandan keyin topshirish uchun beriladigan kunlar soni', null=True),
        ),
    ]
