# Generated by Django 5.2.5 on 2025-10-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_reelsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Foizda'), ('coins', 'FixCoin')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='percent uchun 0-100; coins uchun miqdor', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Cheksiz bo‘lsa bo‘sh qoldiring', null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Moderator tasdiqlaganidan keyin faollashadi'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text="Agar promokod ishlatilgan bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.promocode'),
        ),
    ]
