# Generated by Django 5.2.5 on 2025-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_promocode_course_is_active_coursetype_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='reels/posters/'),
        ),
    ]
