# Generated by Django 5.2.5 on 2025-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_reel_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='courses/videos/posters/'),
        ),
    ]
