# Generated by Django 5.2.5 on 2025-11-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_coursevideo_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='course_types',
            field=models.ManyToManyField(blank=True, to='app.coursetype'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='courses',
            field=models.ManyToManyField(blank=True, to='app.course'),
        ),
    ]
