# Generated by Django 5.2.5 on 2025-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_promocode_course_types_promocode_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chegirma miqdori (musbat)', max_digits=15),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Asl narx', max_digits=15),
        ),
    ]
