# Generated by Django 5.2.5 on 2025-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_reelview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('moderation', 'Moderatsiya'), ('rejected', 'Bekor qilindi'), ('approved', 'Tasdiqlandi')], db_index=True, default='moderation', max_length=20),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='status',
            field=models.CharField(choices=[('moderation', 'Moderatsiya'), ('rejected', 'Bekor qilindi'), ('approved', 'Tasdiqlandi')], db_index=True, default='moderation', max_length=20),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='status',
            field=models.CharField(choices=[('moderation', 'Moderatsiya'), ('rejected', 'Bekor qilindi'), ('approved', 'Tasdiqlandi')], db_index=True, default='moderation', max_length=20),
        ),
    ]
