# Generated by Django 5.2.5 on 2025-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_course_status_coursetype_status_coursevideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
