# Generated by Django 5.2.5 on 2025-11-16 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_course_reason_coursetype_reason_coursevideo_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
