# Generated by Django 5.2.5 on 2025-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_movie_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefile',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
    ]
